// userReducer
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const GOOGLE_LOADING = 'GOOGLE_LOADING';
export const GOOGLE_SUCCESS = 'GOOGLE_SUCCESS';
export const GOOGLE_FAIL = 'GOOGLE_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FORGOT_LOADING = 'FORGOT_LOADING';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAIL = 'FORGOT_FAIL';
export const RESET_LOADING = 'RESET_LOADING';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAIL = 'RESET_FAIL';
export const VERIFY_LOADING = 'VERIFY_LOADING';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAIL = 'VERIFY_FAIL';
export const ADD_USER_LOADING = 'ADD_USER_LOADING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const EDIT_USERS_LOADING = 'EDIT_USERS_LOADING';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAIL = 'EDIT_USERS_FAIL';
export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCESS = 'GET_USERS_SUCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const GET_ONE_USER_LOADING = 'GET_ONE_USER_LOADING';
export const GET_ONE_USER_SUCESS = 'GET_ONE_USER_SUCESS';
export const GET_ONE_USER_FAIL = 'GET_ONE_USER_FAIL';
export const SET_SEARCH_FOLLOW_NOTIFICATION_LOADING = 'SET_SEARCH_FOLLOW_NOTIFICATION_LOADING';
export const SET_SEARCH_FOLLOW_NOTIFICATION_SUCCESS = 'SET_SEARCH_FOLLOW_NOTIFICATION_SUCCESS';
export const SET_SEARCH_FOLLOW_NOTIFICATION_FAIL = 'SET_SEARCH_FOLLOW_NOTIFICATION_FAIL';
export const SET_SEARCH_USER_LOADING = 'SET_SEARCH_USER_LOADING';
export const SET_SEARCH_USER_SUCCESS = 'SET_SEARCH_USER_SUCCESS';
export const SET_SEARCH_USER_FAIL = 'SET_SEARCH_USER_FAIL';
export const SET_CURRENT_PAGE_USER_LOADING = 'SET_CURRENT_PAGE_USER_LOADING';
export const SET_CURRENT_PAGE_USER_SUCCESS = 'SET_CURRENT_PAGE_USER_SUCCESS';
export const SET_CURRENT_PAGE_USER_FAIL = 'SET_CURRENT_PAGE_USER_FAIL';
export const USER_FOLLOW_NOTIFICATION_LOADING = 'USER_FOLLOW_NOTIFICATION_LOADING';
export const USER_FOLLOW_NOTIFICATION_SUCCESS = 'USER_FOLLOW_NOTIFICATION_SUCCESS';
export const USER_FOLLOW_NOTIFICATION_FAIL = 'USER_FOLLOW_NOTIFICATION_FAIL';
export const GET_FOLLOW_NOTIFICATION_LOADING = 'GET_FOLLOW_NOTIFICATION_LOADING';
export const GET_FOLLOW_NOTIFICATION_SUCCESS = 'GET_FOLLOW_NOTIFICATION_SUCCESS';
export const GET_FOLLOW_NOTIFICATION_FAIL = 'GET_FOLLOW_NOTIFICATION_FAIL';
export const SET_CURRENT_PAGE_FOLLOW_NOTIFICATION_LOADING = 'SET_CURRENT_PAGE_FOLLOW_NOTIFICATION_LOADING';
export const SET_CURRENT_PAGE_FOLLOW_NOTIFICATION_SUCCESS = 'SET_CURRENT_PAGE_FOLLOW_NOTIFICATION_SUCCESS';
export const SET_CURRENT_PAGE_FOLLOW_NOTIFICATION_FAIL = 'SET_CURRENT_PAGE_FOLLOW_NOTIFICATION_FAIL';

//appReducer
export const INITIALIZE_APP_LOADING = 'INITIALIZE_APP_LOADING';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';
export const INITIALIZE_APP_FAIL = 'INITIALIZE_APP_FAIL';
export const SET_PAGE_TRANSITION_PROGRESS_BAR_LOADING = 'SET_PAGE_TRANSITION_PROGRESS_BAR_LOADING';
export const SET_PAGE_TRANSITION_PROGRESS_BAR_SUCCESS = 'SET_PAGE_TRANSITION_PROGRESS_BAR_SUCCESS';
export const SET_PAGE_TRANSITION_PROGRESS_BAR_FAIL = 'SET_PAGE_TRANSITION_PROGRESS_BAR_FAIL';


//errorReducer
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//adminReducer
export const GET_ADMINS_LOADING = 'GET_ADMINS_LOADING';
export const GET_ADMINS_SUCCESS = 'GET_ADMINS_SUCCESS';
export const GET_ADMINS_FAIL = 'GET_ADMINS_FAIL';
export const SET_SEARCH_ADMIN_LOADING = 'SET_SEARCH_ADMIN_LOADING';
export const SET_SEARCH_ADMIN_SUCCESS = 'SET_SEARCH_ADMIN_SUCCESS';
export const SET_SEARCH_ADMIN_FAIL = 'SET_SEARCH_ADMIN_FAIL';
export const SET_CURRENT_PAGE_ADMIN_LOADING = 'SET_CURRENT_PAGE_ADMIN_LOADING';
export const SET_CURRENT_PAGE_ADMIN_SUCCESS = 'SET_CURRENT_PAGE_ADMIN_SUCCESS';
export const SET_CURRENT_PAGE_ADMIN_FAIL = 'SET_CURRENT_PAGE_ADMIN_FAIL';


//typeReducer
export const EDIT_TYPE_LOADING = 'EDIT_TYPE_LOADING';
export const EDIT_TYPE_SUCCESS = 'EDIT_TYPE_SUCCESS';
export const EDIT_TYPE_FAIL = 'EDIT_TYPE_FAIL';
export const ADD_TYPE_LOADING = 'ADD_TYPE_LOADING';
export const ADD_TYPE_SUCCESS = 'ADD_TYPE_SUCCESS';
export const ADD_TYPE_FAIL = 'ADD_TYPE_FAIL';
export const DELETE_TYPE_LOADING = 'DELETE_TYPE_LOADING';
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL';
export const GET_TYPES_LOADING = 'GET_TYPES_LOADING';
export const GET_TYPES_SUCESS = 'GET_TYPES_SUCESS';
export const GET_TYPES_FAIL = 'GET_TYPES_FAIL';
export const SET_SELECTED_TYPE_LOADING = 'SET_SELECTED_TYPE_LOADING';
export const SET_SELECTED_TYPE_SUCCESS = 'SET_SELECTED_TYPE_SUCCESS';
export const SET_SELECTED_TYPE_FAIL = 'SET_SELECTED_TYPE_FAIL';
export const SET_SEARCH_TYPE_LOADING = 'SET_SEARCH_TYPE_LOADING';
export const SET_SEARCH_TYPE_SUCCESS = 'SET_SEARCH_TYPE_SUCCESS';
export const SET_SEARCH_TYPE_FAIL = 'SET_SEARCH_TYPE_FAIL';
export const SET_CURRENT_PAGE_TYPE_LOADING = 'SET_CURRENT_PAGE_TYPE_LOADING';
export const SET_CURRENT_PAGE_TYPE_SUCCESS = 'SET_CURRENT_PAGE_TYPE_SUCCESS';
export const SET_CURRENT_PAGE_TYPE_FAIL = 'SET_CURRENT_PAGE_TYPE_FAIL';

//brandReducer
export const EDIT_BRAND_LOADING = 'EDIT_BRAND_LOADING';
export const EDIT_BRAND_SUCCESS = 'EDIT_BRAND_SUCCESS';
export const EDIT_BRAND_FAIL = 'EDIT_BRAND_FAIL';
export const ADD_BRAND_LOADING = 'ADD_BRAND_LOADING';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const ADD_BRAND_FAIL = 'ADD_BRAND_FAIL';
export const DELETE_BRAND_LOADING = 'DELETE_BRAND_LOADING';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';
export const GET_BRANDS_LOADING = 'GET_BRANDS_LOADING';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAIL = 'GET_BRANDS_FAIL';
export const SET_SELECTED_BRAND_LOADING = 'SET_SELECTED_BRAND_LOADING';
export const SET_SELECTED_BRAND_SUCCESS = 'SET_SELECTED_BRAND_SUCCESS';
export const SET_SELECTED_BRAND_FAIL = 'SET_SELECTED_BRAND_FAIL';
export const SET_SEARCH_BRAND_LOADING = 'SET_SEARCH_BRAND_LOADING';
export const SET_SEARCH_BRAND_SUCCESS = 'SET_SEARCH_BRAND_SUCCESS';
export const SET_SEARCH_BRAND_FAIL = 'SET_SEARCH_BRAND_FAIL';
export const SET_CURRENT_PAGE_BRAND_LOADING = 'SET_CURRENT_PAGE_BRAND_LOADING';
export const SET_CURRENT_PAGE_BRAND_SUCCESS = 'SET_CURRENT_PAGE_BRAND_SUCCESS';
export const SET_CURRENT_PAGE_BRAND_FAIL = 'SET_CURRENT_PAGE_BRAND_FAIL';

//deviceReducer
export const EDIT_DEVICE_LOADING = 'EDIT_DEVICE_LOADING';
export const EDIT_DEVICE_SUCCESS = 'EDIT_DEVICE_SUCCESS';
export const EDIT_DEVICE_FAIL = 'EDIT_DEVICE_FAIL';
export const ADD_DEVICE_LOADING = 'ADD_DEVICE_LOADING';
export const ADD_DEVICE_SUCCESS = 'ADD_DEVICE_SUCCESS';
export const ADD_DEVICE_FAIL = 'ADD_DEVICE_FAIL';
export const DELETE_DEVICE_LOADING = 'DELETE_DEVICE_LOADING';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_FAIL = 'DELETE_DEVICE_FAIL';
export const GET_DEVICES_LOADING = 'GET_DEVICES_LOADING';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAIL = 'GET_DEVICES_FAIL';
export const GET_ONE_DEVICE_LOADING = 'GET_ONE_DEVICE_LOADING';
export const GET_ONE_DEVICE_SUCCESS = 'GET_ONE_DEVICE_SUCCESS';
export const GET_ONE_DEVICE_FAIL = 'GET_ONE_DEVICE_FAIL';
export const SET_SEARCH_DEVICE_LOADING = 'SET_SEARCH_DEVICE_LOADING';
export const SET_SEARCH_DEVICE_SUCCESS = 'SET_SEARCH_DEVICE_SUCCESS';
export const SET_SEARCH_DEVICE_FAIL = 'SET_SEARCH_DEVICE_FAIL';
export const SET_CURRENT_PAGE_DEVICE_LOADING = 'SET_CURRENT_PAGE_DEVICE_LOADING';
export const SET_CURRENT_PAGE_DEVICE_SUCCESS = 'SET_CURRENT_PAGE_DEVICE_SUCCESS';
export const SET_CURRENT_PAGE_DEVICE_FAIL = 'SET_CURRENT_PAGE_DEVICE_FAIL';

//sort
export const SET_SORT_LOADING = 'SET_SORT_LOADING';
export const SET_SORT_SUCCESS = 'SET_SORT_SUCCESS';
export const SET_SORT_FAIL = 'SET_SORT_FAIL';

//filterPriceRange
export const FILTER_PRICE_RANGE_LOADING = 'FILTER_PRICE_RANGE_LOADING';
export const FILTER_PRICE_RANGE_SUCCESS = 'FILTER_PRICE_RANGE_SUCCESS';
export const FILTER_PRICE_RANGE_FAIL = 'FILTER_PRICE_RANGE_FAIL';

//filterRatingRange
export const FILTER_RATING_RANGE_LOADING = 'FILTER_RATING_RANGE_LOADING';
export const FILTER_RATING_RANGE_SUCCESS = 'FILTER_RATING_RANGE_SUCCESS';
export const FILTER_RATING_RANGE_FAIL = 'FILTER_RATING_RANGE_FAIL';

//notification
export const SET_NOTIFICATION_LOADING = 'SET_NOTIFICATION_LOADING';
export const SET_NOTIFICATION_SUCCESS = 'SET_NOTIFICATION_SUCCESS';
export const SET_NOTIFICATION_FAIL = 'SET_NOTIFICATION_FAIL';
export const GET_NOTIFICATION_LOADING = 'GET_NOTIFICATION_LOADING';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';
export const DELETE_NOTIFICATION_LOADING = 'DELETE_NOTIFICATION_LOADING';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_FAIL';
export const DELETE_ALL_NOTIFICATION_LOADING = 'DELETE_ALL_NOTIFICATION_LOADING';
export const DELETE_ALL_NOTIFICATION_SUCCESS = 'DELETE_ALL_NOTIFICATION_SUCCESS';
export const DELETE_ALL_NOTIFICATION_FAIL = 'DELETE_ALL_NOTIFICATION_FAIL';
export const SET_CURRENT_PAGE_NOTIFICATION_LOADING = 'SET_CURRENT_PAGE_NOTIFICATION_LOADING';
export const SET_CURRENT_PAGE_NOTIFICATION_SUCCESS = 'SET_CURRENT_PAGE_NOTIFICATION_SUCCESS';
export const SET_CURRENT_PAGE_NOTIFICATION_FAIL = 'SET_CURRENT_PAGE_NOTIFICATION_FAIL';
export const SET_SEARCH_NOTIFICATION_LOADING = 'SET_SEARCH_NOTIFICATION_LOADING';
export const SET_SEARCH_NOTIFICATION_SUCCESS = 'SET_SEARCH_NOTIFICATION_SUCCESS';
export const SET_SEARCH_NOTIFICATION_FAIL = 'SET_SEARCH_NOTIFICATION_FAIL';
export const SET_SORT_NOTIFICATION_LOADING = 'SET_SORT_NOTIFICATION_LOADING';
export const SET_SORT_NOTIFICATION_SUCCESS = 'SET_SORT_NOTIFICATION_SUCCESS';
export const SET_SORT_NOTIFICATION_FAIL = 'SET_SORT_NOTIFICATION_FAIL';

//cartReducer 
export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const REMOVE_FROM_CART_LOADING = 'REMOVE_FROM_CART_LOADING';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAIL = 'REMOVE_FROM_CART_FAIL';
export const CART_RESET_LOADING = 'CART_RESET_LOADING';
export const CART_RESET_SUCCESS = 'CART_RESET_SUCCESS';
export const CART_RESET_FAIL = 'CART_RESET_FAIL';
export const SET_CART_LOADING = 'SET_CART_LOADING';
export const SET_CART_SUCCESS = 'SET_CART_SUCCESS';
export const SET_CART_FAIL = 'SET_CART_FAIL';

//deliveryReducer

export const ADD_TO_DELIVERY_LOADING = 'ADD_TO_DELIVERY_LOADING';
export const ADD_TO_DELIVERY_SUCCESS = 'ADD_TO_DELIVERY_SUCCESS';
export const ADD_TO_DELIVERY_FAIL = 'ADD_TO_DELIVERY_FAIL';
export const SET_DELIVERY_LOADING = 'SET_DELIVERY_LOADING';
export const SET_DELIVERY_SUCCESS = 'SET_DELIVERY_SUCCESS';
export const SET_DELIVERY_FAIL = 'SET_DELIVERY_FAIL';


//wishListReducer 
export const ADD_TO_WISHLIST_LOADING = 'ADD_TO_WISHLIST_LOADING';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';
export const REMOVE_FROM_WISHLIST_LOADING = 'REMOVE_FROM_WISHLIST_LOADING';
export const REMOVE_FROM_WISHLIST_SUCCESS = 'REMOVE_FROM_WISHLIST_SUCCESS';
export const REMOVE_FROM_WISHLIST_FAIL = 'REMOVE_FROM_WISHLIST_FAIL';
export const WISHLIST_RESET_LOADING = 'WISHLIST_RESET_LOADING';
export const WISHLIST_RESET_SUCCESS = 'WISHLIST_RESET_SUCCESS';
export const WISHLIST_RESET_FAIL = 'WISHLIST_RESET_FAIL';
export const SET_WISHLIST_LOADING = 'SET_WISHLIST_LOADING';
export const SET_WISHLIST_SUCCESS = 'SET_WISHLIST_SUCCESS';
export const SET_WISHLIST_FAIL = 'SET_WISHLIST_FAIL';